### ISSUE TITLE
Prevent `.` imports

### ISSUE THREAD

**Issue by david-zacharias** [werk85/eslint-config-werk85#22]
`import … from '.'` can be prevented by using [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports) with following rule configuration:

```
'no-restricted-imports': [
  'error',
  {
    paths: ['.']
  }
]
```

Result:

![Bildschirmfoto 2021-10-11 um 10 17 22](https://user-images.githubusercontent.com/1903179/136758278-b5aad3cb-c991-421d-928a-a09843971e7b.png)

**Comment by mlegenhausen** [comment]
Released in 4.4.0.
